import ConstructionSite from '@/components/construction-site';
import FlipCard from '@/components/flip-card';

const aiCards = [
  { tag: 'COURSEWORK', n: '01', title: 'AI in Construction', text: 'Part of my ASU graduate coursework, alongside project controls, estimation, and BIM. This section will document course projects and the lessons I can bring back to a project team.', pending: 'Course deliverables to follow' },
  { tag: 'ACADEMIC PROJECT', n: '02', title: 'Building for AI', text: 'My Spine-Leaf AI Data Center proposal explores a 10+ MW modular facility, hybrid cooling, and GPU-dense racks. This is a study of infrastructure for AI, distinct from using AI tools to manage construction.', link: '#projects', linkLabel: 'Explore the project summary ↗' },
  { tag: 'CASE STUDIES & EXPERIMENTS', n: '03', title: 'Documenting the learning.', text: 'A growing space for practical investigations: the construction problem, the method, the result, and the limits. Detailed case studies and experiment results have not been published yet.', pending: 'Entries to follow' },
];
const linkedin = 'https://www.linkedin.com/in/vishwajeet-u-patil/';
const experience = [
  { company: 'FILANC Construction Co.', role: 'Project Engineer Intern', location: 'Phoenix, Arizona', dates: 'May 2026 – Present', bullets: [
    'Support project engineers across five active municipal water infrastructure projects in Phoenix, Avondale, Peoria, Mesa, and San Luis.',
    'Assisted estimating and subcontractor selection for a $60M+ water treatment facility in San Luis, coordinating mechanical, electrical, plumbing, civil, structural, and architectural scopes and flagging 15+ RFIs.',
    'Closed 100+ RFIs and 300+ submittals; supported owner turnover, as-built drawings, QA/QC inspections, and maintenance-of-plant-operations walks.',
    'Secured 90% approvals for 100+ preconstruction submittals and RFIs within a month, contributing to 80% on-time material delivery; assisted six-week look-ahead schedules.',
    'Managed 100+ cut sheet approvals for the Union Hills WTP Training Facility within 30 days. Built a concurrent O&M documentation process that reduced Peoria closeout preparation effort by approximately 50%.',
  ]},
  { company: 'Arizona State University', role: 'Graduate Student Assistant · Prefab & Offsite Manufacturing', location: 'Prof. Ron Rendina', dates: 'Aug 2026 – Present', bullets: [
    'Support a class of 20 students through guest lecture coordination and site tours of prefab manufacturing facilities at TSMC, Intel, and DPR.',
    'Assist with presentations, exams, assignments, syllabus documentation, and meeting minutes.',
  ]},
  { company: 'Arizona Water Innovation Initiative · ASU', role: 'Research Aide', location: 'Phoenix, Arizona', dates: 'Oct 2025 – Jun 2026', bullets: [
    'Assessed irrigation systems across 20+ freeway corridors and developed corrective action plans targeting 15–20% water savings, or approximately 7M+ gallons annually.',
    'Managed field logistics, resolved on-site clashes, and practiced OSHA standards. Water savings are research targets, not measured outcomes.',
  ]},
  { company: 'D+J Design Studio', role: 'Project Design Engineer · Resort Project', location: 'Nashik, India', dates: 'Jan 2025 – Aug 2025', bullets: [
    'Approved 50+ subcontractor quotes and executed approximately $150K in purchase orders for pool and adventure park equipment.',
    'Identified two structural nonconformances during casting of a reinforced-concrete bridge, helping avoid approximately $20K in rework.',
    'Estimated and scheduled a 250-person restaurant and 8,000-gallon swimming pool; coordinated filtration installation, RFIs, shop drawings, and field sequencing.',
  ]},
  { company: 'Tor Vergata University of Rome', role: 'Architectural Intern', location: 'Rome, Italy', dates: 'Jun 2023 – Jul 2023', bullets: [
    'Developed a 32,000 sq. ft. urban design proposal and a construction documentation package of more than 20 sheets.',
    'Designed a 15,000 sq. ft. student facility and prepared architectural, structural, and site drawings for stakeholder review.',
  ]},
];
const projects = [
  { n: '01', type: 'PROFESSIONAL · FILANC', title: 'Municipal water infrastructure', location: 'Arizona · 2026', text: 'Field engineering and project coordination across five active municipal projects, from preconstruction through owner turnover.', facts: ['$60M+ San Luis facility', '100+ RFIs closed', '300+ submittals closed'], note: 'My contribution: estimating support, scope coordination, procurement follow-through, QA/QC, and closeout documentation.' },
  { n: '02', type: 'PROFESSIONAL · D+J DESIGN STUDIO', title: 'Resort construction & site coordination', location: 'Nashik, India · 2025', text: 'Restaurant, pool, and adventure park works that brought design documentation into the realities of subcontractor coordination and field sequencing.', facts: ['50+ subcontractor quotes', '~$150K purchase orders', '~$20K rework avoided'], note: 'My contribution: estimating, scheduling, procurement, drawing reviews, and identifying structural nonconformances.' },
  { n: '03', type: 'ACADEMIC · ARIZONA STATE UNIVERSITY', title: 'Spine-Leaf AI Data Center', location: 'Mission-critical facilities · 2025–26', text: 'A modular, GPU-dense facility concept exploring the cooling, power, and redundancy requirements of AI infrastructure.', facts: ['10+ MW', '80 kW / rack', '1.2 design PUE'], note: 'Academic design parameters: hybrid cooling and N+2N redundancy. These describe a course proposal, not an operating facility.' },
  { n: '04', type: 'ACADEMIC · ARIZONA STATE UNIVERSITY', title: 'LabSPEC Semiconductor Pilot Facility', location: 'Design-build proposal · 2025–26', text: 'A 125,000 sq. ft. semiconductor pilot facility proposal bringing cleanroom performance and vibration control into the construction discussion.', facts: ['125,000 sq. ft.', 'ISO 3/4 cleanroom', 'Vibration-control foundation'], note: 'Academic proposal with active and passive vibration control. Project drawings and detailed deliverables will be added as the portfolio develops.' },
];
export default function Home() {
  return <><ConstructionSite />
    <a className="skip" href="#main">Skip to content</a>
    <header id="top"><a className="brand" href="#top">Vishwajeet Patil<span>.</span></a><nav aria-label="Main navigation"><a href="#about">About</a><a href="#experience">Experience</a><a href="#projects">Projects</a><a href="#skills">Skills</a><a href="#ai">AI & learning</a></nav><a className="connect" href="#contact">Let’s connect ↗</a></header>
    <main id="main">
      <section className="hero" id="home">
        <div><p className="eyebrow">CONSTRUCTION MANAGEMENT · PROJECT ENGINEERING</p><h1>From design intent<br/>to <em>on-site impact.</em></h1><p className="intro">I’m Vishwajeet Unmesh Patil, an architect turned construction management graduate student at ASU. I bring hands-on project engineering experience across five municipal water infrastructure projects—and a habit of following the details through.</p><p className="availability">Based in Tempe, AZ · Seeking construction management and project engineer jobs & internships.</p><div className="actions"><a className="button" href="/Vishwajeet-Patil-Resume.pdf" download>Download resume ↓</a><a href="#experience">See my experience ↗</a></div></div>
        <div className="hero-foot"><span>FIELD COORDINATION / PROJECT CONTROLS / QUALITY</span><span>OSHA 30 · CMIT · LEED GREEN ASSOCIATE</span></div>
      </section>
      <section className="section" id="about"><p className="label">01 / ABOUT</p><div><h2>I like knowing how it’s designed.<br/><span>I care about how it gets built.</span></h2><div className="columns"><p>My path started with architecture in India, took me to a design internship in Rome, and brought me to construction management at Arizona State University. Working on a resort in Nashik moved that interest into the field: subcontractor quotes, purchase orders, concrete inspections, and decisions that could prevent rework.</p><p>Today, at FILANC, I help keep water infrastructure projects moving—from RFIs and submittals to procurement and owner turnover. I enjoy connecting the drawing to the site, asking the next question, and making information easier for the team to act on. That same curiosity draws me to offsite manufacturing, mission-critical facilities, and AI in construction.</p></div><div className="journey"><div><small>FIELD EXPERIENCE</small><h3>5 active projects</h3><p>Municipal water infrastructure with FILANC.</p></div><div><small>PROJECT FOLLOW-THROUGH</small><h3>~50% less effort</h3><p>Closeout preparation through concurrent O&M documentation.</p></div><div><small>ACADEMIC FOUNDATION</small><h3>4.00 GPA</h3><p>M.S. Construction Management & Technology at ASU.</p></div></div></div></section>
      <section className="section" id="experience"><p className="label">02 / EXPERIENCE</p><div><h2>Close to the field.<br/><span>Accountable to the details.</span></h2><p className="section-intro">Experience spanning water infrastructure, resort construction, research, and architectural documentation.</p>{experience.map(job => <article className="job" key={job.role}><div className="job-heading"><div><p className="job-company">{job.company}</p><h3>{job.role}</h3></div><div className="job-meta"><span>{job.dates}</span><span>{job.location}</span></div></div><ul>{job.bullets.map(b => <li key={b}>{b}</li>)}</ul></article>)}</div></section>
      <section className="section" id="projects"><p className="label">03 / SELECTED WORK</p><div><h2>Projects with practical stakes.</h2><p className="section-intro">Professional contributions and academic proposals, connected by an interest in complex systems and disciplined delivery.</p><div className="project-grid">{projects.map(p => <article className="portfolio-project" key={p.n}><div className="card-top"><span>{p.type}</span><span>{p.n}</span></div><h3>{p.title}</h3><p className="project-location">{p.location}</p><p>{p.text}</p><ul className="project-facts">{p.facts.map(f => <li key={f}>{f}</li>)}</ul><p className="project-note">{p.note}</p></article>)}</div></div></section>
      <section className="section" id="skills"><p className="label">04 / SKILLS & CREDENTIALS</p><div><h2>The tools behind the follow-through.</h2><p className="section-intro">Construction coordination and controls, supported by a foundation in drawings and BIM.</p><div className="skills-grid">{[['Project controls','Estimating & quantity takeoff','Scheduling & look-ahead planning','Cost control & resource allocation','Change orders'],['Field & documentation','RFIs & submittals','QA/QC inspections','Shop drawings & as-built markups','O&M and closeout documentation'],['Software & BIM','Procore · Bluebeam · InEight','Primavera P6 · Excel','Navisworks · Revit · AutoCAD','Word · PowerPoint · BIM modeling']].map(([title,...items]) => <FlipCard key={title} front={<h3>{title}</h3>} back={<><h3>{title}</h3>{items.map(item => <p key={item}>{item}</p>)}</>} />)}</div><div className="credentials"><h3>Certifications & registration</h3><ul>{['OSHA 30-Hour','CMAA · Construction Manager in Training (CMIT)','LEED Green Associate','Procore · Project Management','Bluebeam Certified Professional','Council of Architecture, India · CA/2024/178815'].map(c => <li key={c}>{c}</li>)}</ul></div></div></section>
      <section className="section" id="education"><p className="label">05 / EDUCATION & LEADERSHIP</p><div><h2>Learning with a team.<br/><span>Leading through the work.</span></h2><div className="resume-row"><small>AUG 2025 – MAY 2027<br/>EXPECTED</small><div><h3>M.S. Construction Management & Technology</h3><p className="school">Arizona State University · Del E. Webb School of Construction · GPA 4.00</p><p>Mission-critical facilities, AI in Construction, BIM and offsite manufacturing, advanced project controls, and estimation.</p></div></div><div className="resume-row"><small>JUN 2019 – MAY 2024</small><div><h3>B.S. Architecture</h3><p className="school">MIT ADT School of Architecture, India · GPA 3.70</p><p>Architectural design, BIM modeling, building codes, urban design, industrial design, and computational design.</p></div></div><div className="leadership-grid"><article><small>ASC COMPETITION · TEAM CAPTAIN</small><h3>Eight tasks. Nine hours. One team.</h3><p>Third place in the 2026 ASC Alternates Competition, completing eight project control tasks in nine hours through collaboration with a diverse team. Captain for the 2026–27 competition.</p><p className="tenure">September 2025 – Present</p></article><article><small>IFMA · VICE PRESIDENT</small><h3>Building connections beyond the site.</h3><p>Vice President of the IFMA Greater Phoenix Student Chapter, connecting with professionals and peers across facility management and the built environment.</p><p className="tenure">April 2026 – Present</p></article></div></div></section>
      <section className="ai" id="ai"><div className="section-heading"><div><p className="eyebrow">06 / AI IN CONSTRUCTION</p><h2>Curious about what’s next.<br/>Grounded in what a project needs.</h2></div><p>My AI interests grow out of construction: better information, informed decisions, and the infrastructure behind new technology.</p></div><div className="ai-grid">{aiCards.map(card => <FlipCard key={card.n}
        front={<><div className="card-top"><span>{card.tag}</span><span>{card.n}</span></div><h3>{card.title}</h3></>}
        back={<><div className="card-top"><span>{card.tag}</span><span>{card.n}</span></div><p>{card.text}</p>{card.link ? <a className="ai-link" href={card.link}>{card.linkLabel}</a> : <span className="pending">{card.pending}</span>}</>}
      />)}</div></section>
      <section className="section" id="journal"><p className="label">07 / NOTES & ARTICLES</p><div><h2>Learning beyond the job description.</h2><p className="section-intro">I share professional updates on LinkedIn, including water conservation research, water reuse technology, and student leadership.</p><div className="journal-entry"><span>↗</span><div><h3>Water infrastructure, research & people.</h3><p>Recent updates reflect an interest in sustainable water infrastructure and learning from utilities, researchers, engineers, and contractors. Longer articles and course reflections will be collected here as they’re published.</p><a className="inline-link" href={linkedin} target="_blank" rel="noopener noreferrer">Read my LinkedIn updates ↗</a></div></div></div></section>
      <section className="contact" id="contact"><p className="eyebrow">08 / LET’S CONNECT</p><h2>Let’s get the next<br/><em>project moving.</em></h2><div className="contact-bottom"><div><p>I’m seeking construction management and project engineer jobs and internships, with interests in water infrastructure, mission-critical facilities, and complex building projects.</p><p className="contact-location">Tempe, Arizona · M.S. expected May 2027</p><a className="inline-link" href="/Vishwajeet-Patil-Resume.pdf" download>Download my resume (PDF) ↓</a></div><address><a href="mailto:vpatil37@asu.edu">vpatil37@asu.edu ↗</a><a href="tel:+14804345322">+1 (480) 434-5322</a><a href={linkedin} target="_blank" rel="noopener noreferrer">Connect on LinkedIn ↗</a></address></div></section>
    </main><footer><a className="brand" href="#top">Vishwajeet Patil<span>.</span></a><small>CONSTRUCTION MANAGEMENT · PROJECT ENGINEERING</small><a href="#top">Back to top ↑</a></footer>
  </>;
}
